// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
    production: false,
    googleApiKey: null,
    googleApiServiceAccount: null,
    events: [
        {
            title: 'Paolo',
            start: '2020-11-25T16:00:00',
            end: '2020-11-25T18:00:00',
            extendedProps: {
                description: 'Esami',
            }
        },
        {
            title: 'Daniele',
            start: '2020-11-26T16:00:00',
            end: '2020-11-26T18:00:00',
            extendedProps: {
                description: 'Istruzionale',
            }
        },
        {
            title: 'Manuel',
            start: '2020-11-27T18:00:00',
            end: '2020-11-27T23:00:00',
            extendedProps: {
                description: 'Volo notturno con testo lungo descrizione lunghissima non sapevo cosa scrivere',
            }
        },
        {
            title: 'Claudia',
            start: '2020-11-20T09:00:00',
            end: '2020-11-20T10:00:00',
        },
    ],
    flightlog: [
        {
            date: new Date(2020, 11, 1),
            pilot: 'Ultimo',
            origin: 'Fly Roma',
            destination: 'Alituscia',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 2),
            pilot: 'Paola',
            origin: 'Alituscia',
            destination: 'Santa Severa',
            startHour: 1967,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 3),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 0,
            notes: '',
        },
        {
            date: new Date(2020, 11, 4),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 0,
            notes: '',
        },
        {
            date: new Date(2020, 11, 5),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 6),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 7),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 8),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 9),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 10),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 11),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 12),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 13),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 14),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 15),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 16),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 17),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 18),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 19),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 20),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 21),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 22),
            pilot: 'Daniele',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
        {
            date: new Date(2020, 11, 23),
            pilot: 'Primo',
            origin: 'Fly Roma',
            destination: 'Fly Roma',
            startHour: 1967.60,
            endHour: 1969.80,
            fuel: 16,
            notes: '',
        },
    ],
    pilots: [
        'Claudia',
        'Daniele',
        'Davide',
        'Manuel',
        'Paolo',
        'Simone',
        'Victoriano',
    ],
    location: {
        name: 'Fly Roma',
        // Fly Roma coordinates and height (190 ft)
        latitude: 41.88,
        longitude: 12.71,
        height: 58
    },
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
